import Foundation

public struct BedrockAddOnArchive: Sendable {
    public let entries: [ZipArchiveEntry]
}

public struct BedrockAddOnArtifact: Sendable {
    public let url: URL
    public let identifier: BedrockIdentifier
    public let fileName: String
}

public final class BedrockAddOnCompiler: Sendable {
    private let suffixGenerator: @Sendable () -> String
    private let uuidGenerator: @Sendable () -> UUID

    public init(
        suffixGenerator: @escaping @Sendable () -> String = { String(UUID().uuidString.prefix(6)).lowercased() },
        uuidGenerator: @escaping @Sendable () -> UUID = { UUID() }
    ) {
        self.suffixGenerator = suffixGenerator
        self.uuidGenerator = uuidGenerator
    }

    public func compile(_ specification: SwordSpec, outputDirectory: URL) throws -> BedrockAddOnArtifact {
        let identifier = BedrockIdentifier.make(displayName: specification.displayName, suffix: suffixGenerator())
        let archive = try buildArchive(specification, identifier: identifier)
        try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        let outputURL = outputDirectory.appending(path: "\(identifier.pathComponent).mcaddon")
        let archiveData = try ZipArchiveWriter.archive(entries: archive.entries)
        try archiveData.write(to: outputURL, options: .atomic)
        return BedrockAddOnArtifact(url: outputURL, identifier: identifier, fileName: outputURL.lastPathComponent)
    }

    public func buildArchive(_ specification: SwordSpec) throws -> BedrockAddOnArchive {
        let identifier = BedrockIdentifier.make(displayName: specification.displayName, suffix: suffixGenerator())
        return try buildArchive(specification, identifier: identifier)
    }

    private func buildArchive(_ specification: SwordSpec, identifier: BedrockIdentifier) throws -> BedrockAddOnArchive {
        let behaviorHeaderUUID = uuidGenerator().uuidString.lowercased()
        let behaviorModuleUUID = uuidGenerator().uuidString.lowercased()
        let resourceHeaderUUID = uuidGenerator().uuidString.lowercased()
        let resourceModuleUUID = uuidGenerator().uuidString.lowercased()
        let resourceName = "\(identifier.pathComponent)_resources"
        let behaviorName = "\(identifier.pathComponent)_behavior"

        let behaviorEntries = try behaviorPackEntries(
            specification: specification,
            identifier: identifier,
            behaviorHeaderUUID: behaviorHeaderUUID,
            behaviorModuleUUID: behaviorModuleUUID,
            resourceHeaderUUID: resourceHeaderUUID
        )
        let resourceEntries = try resourcePackEntries(
            specification: specification,
            identifier: identifier,
            resourceHeaderUUID: resourceHeaderUUID,
            resourceModuleUUID: resourceModuleUUID
        )

        return BedrockAddOnArchive(entries: [
            ZipArchiveEntry(path: "\(behaviorName).mcpack", data: try ZipArchiveWriter.archive(entries: behaviorEntries)),
            ZipArchiveEntry(path: "\(resourceName).mcpack", data: try ZipArchiveWriter.archive(entries: resourceEntries))
        ])
    }

    private func behaviorPackEntries(
        specification: SwordSpec,
        identifier: BedrockIdentifier,
        behaviorHeaderUUID: String,
        behaviorModuleUUID: String,
        resourceHeaderUUID: String
    ) throws -> [ZipArchiveEntry] {
        let version: [Int] = [1, 0, 0]
        let localizationKey = "item.\(identifier.rawValue).name"
        let manifest: [String: Any] = [
            "format_version": 2,
            "header": [
                "name": "\(specification.displayName) Behavior",
                "description": "Generated by Craftberry",
                "uuid": behaviorHeaderUUID,
                "version": version,
                "min_engine_version": [1, 21, 80]
            ],
            "modules": [[
                "type": "data",
                "uuid": behaviorModuleUUID,
                "version": version
            ]],
            "dependencies": [[
                "uuid": resourceHeaderUUID,
                "version": version
            ]]
        ]
        let item: [String: Any] = [
            "format_version": "1.21.80",
            "minecraft:item": [
                "description": [
                    "identifier": identifier.rawValue,
                    "menu_category": ["category": "equipment", "group": "itemGroup.name.sword"]
                ],
                "components": [
                    "minecraft:display_name": ["value": localizationKey],
                    "minecraft:icon": ["textures": ["default": identifier.pathComponent]],
                    "minecraft:max_stack_size": 1,
                    "minecraft:hand_equipped": true,
                    "minecraft:damage": ["value": specification.attackBonus],
                    "minecraft:durability": [
                        "max_durability": specification.durability,
                        "damage_chance": ["min": 100, "max": 100]
                    ]
                ]
            ]
        ]
        let recipe: [String: Any] = [
            "format_version": "1.20.10",
            "minecraft:recipe_shaped": [
                "description": ["identifier": "\(identifier.rawValue)_recipe"],
                "tags": ["crafting_table"],
                "pattern": [" M ", " M ", " S "],
                "key": [
                    "M": ["item": specification.craftingIngredient.bedrockIdentifier],
                    "S": ["item": "minecraft:stick"]
                ],
                "result": ["item": identifier.rawValue, "count": 1]
            ]
        ]
        return [
            ZipArchiveEntry(path: "manifest.json", data: try json(manifest)),
            ZipArchiveEntry(path: "items/\(identifier.pathComponent).json", data: try json(item)),
            ZipArchiveEntry(path: "recipes/\(identifier.pathComponent).json", data: try json(recipe)),
            ZipArchiveEntry(path: "pack_icon.png", data: SwordTextureRenderer.render(specification, pixelScale: 4))
        ]
    }

    private func resourcePackEntries(
        specification: SwordSpec,
        identifier: BedrockIdentifier,
        resourceHeaderUUID: String,
        resourceModuleUUID: String
    ) throws -> [ZipArchiveEntry] {
        let version: [Int] = [1, 0, 0]
        let manifest: [String: Any] = [
            "format_version": 2,
            "header": [
                "name": "\(specification.displayName) Resources",
                "description": "Generated by Craftberry",
                "uuid": resourceHeaderUUID,
                "version": version,
                "min_engine_version": [1, 21, 80]
            ],
            "modules": [[
                "type": "resources",
                "uuid": resourceModuleUUID,
                "version": version
            ]]
        ]
        let textureMap: [String: Any] = [
            "resource_pack_name": "\(specification.displayName) Resources",
            "texture_data": [
                identifier.pathComponent: ["textures": "textures/items/\(identifier.pathComponent)"]
            ]
        ]
        return [
            ZipArchiveEntry(path: "manifest.json", data: try json(manifest)),
            ZipArchiveEntry(path: "textures/item_texture.json", data: try json(textureMap)),
            ZipArchiveEntry(path: "textures/items/\(identifier.pathComponent).png", data: SwordTextureRenderer.render(specification)),
            ZipArchiveEntry(path: "texts/languages.json", data: try json(["en_US"])),
            ZipArchiveEntry(
                path: "texts/en_US.lang",
                data: Data("item.\(identifier.rawValue).name=\(specification.displayName)\n".utf8)
            ),
            ZipArchiveEntry(path: "pack_icon.png", data: SwordTextureRenderer.render(specification, pixelScale: 4))
        ]
    }

    private func json(_ object: Any) throws -> Data {
        var data = try JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .sortedKeys])
        data.append(10)
        return data
    }
}
