#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/.build/minecraft-cleanup"
BUNDLE_ID="com.mojang.minecraftpe"
WORLD_NAME="My World"
CRAFTBERRY_MARKER="Generated by Craftberry"
# Confirmed live: afcclient's --documents house-arrest root is one level
# above what Finder's file-sharing pane displays — Finder shows the
# contents of "Documents/", not the house-arrest root itself.
AFC_BASE="Documents/games/com.mojang"

usage() {
    cat <<USAGE
Usage: scripts/minecraft-cleanup.sh <status|clean> [--yes]

Cleans up Craftberry-generated Minecraft Bedrock test packs directly from
Minecraft's shared Documents directory on the connected iPhone, using
afcclient (part of libimobiledevice) to talk to the device's AFC/House
Arrest service directly — no macFUSE, no kernel extension, no Recovery
Mode / Reduced Security changes required. This bypasses Minecraft's own
in-game pack-removal UI entirely, which can only deactivate a pack for one
world, never uninstall it from the device (see docs/CLEANUP_HANDOFF.md).

Modes:
  status   Read-only. Lists every installed behavior/resource pack, whether
           its manifest carries the Craftberry-generated marker, and
           whether "$WORLD_NAME" still references it (if that world still
           exists). Changes nothing.
  clean    Deletes every Craftberry-generated pack folder (manifest
           description "$CRAFTBERRY_MARKER") from behavior_packs/ and
           resource_packs/. If "$WORLD_NAME" still exists, also resets its
           world_behavior_packs.json / world_resource_packs.json to [] —
           the world directory itself is preserved either way. Requires
           --yes.

Requires: afcclient (brew tap gromgit/fuse && brew install ifuse-mac pulls
it in as a libimobiledevice dependency), jq.

Constraints:
  - Minecraft must be fully quit on the device first — confirmed live that
    AFC's view of Minecraft's own directories is unreliable while the app
    is running (e.g. minecraftWorlds can appear empty). This script does
    not check that for you; quit Minecraft (or
    'xcrun devicectl device process terminate --device <id> --pid <pid>')
    before running either mode.
  - Never touches a pack folder without the exact Craftberry marker.
  - Never deletes the world directory itself, only resets its pack
    reference lists.
USAGE
}

require_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: required tool '$1' was not found on PATH" >&2
        exit 1
    fi
}

afc() {
    # Confirmed live: afcclient's getopt-style parser reorders arguments and
    # trips over subcommand flags like `rm -rf` (misreads -rf as an unknown
    # top-level option) unless `--` explicitly stops option parsing first.
    afcclient --documents "$BUNDLE_ID" -- "$@"
}

# Lists immediate child names of an AFC directory, one per line.
afc_ls() {
    afc ls "$1" 2>/dev/null || true
}

# Downloads a remote file to a local temp path; prints the local path, or
# nothing (and a non-zero exit) if it doesn't exist / can't be read.
afc_get_to_temp() {
    local remote="$1" local_name="$2" local_path
    local_path="$OUTPUT_DIR/tmp/$local_name"
    mkdir -p "$(dirname "$local_path")"
    rm -f "$local_path"
    if afc get "$remote" "$local_path" >/dev/null 2>&1 && [[ -f "$local_path" ]]; then
        printf '%s\n' "$local_path"
        return 0
    fi
    return 1
}

find_world_dir_name() {
    local name dir
    for name in $(afc_ls "$AFC_BASE/minecraftWorlds"); do
        dir="$AFC_BASE/minecraftWorlds/$name"
        local level_file
        if level_file="$(afc_get_to_temp "$dir/levelname.txt" "levelname-$name.txt")"; then
            if [[ "$(cat "$level_file")" == "$WORLD_NAME" ]]; then
                printf '%s\n' "$name"
                return 0
            fi
        fi
    done
    return 1
}

pack_ids_referenced_by_world() {
    local world_dir="$1" file="$2" local_path
    if local_path="$(afc_get_to_temp "$world_dir/$file" "$(basename "$world_dir")-$file")"; then
        jq -r '.[]?.pack_id' "$local_path" 2>/dev/null
    fi
}

report_packs() {
    local kind="$1" active_ids="$2"
    local name manifest_local uuid pack_name description marker active
    for name in $(afc_ls "$AFC_BASE/${kind}_packs"); do
        if ! manifest_local="$(afc_get_to_temp "$AFC_BASE/${kind}_packs/$name/manifest.json" "${kind}-$name-manifest.json")"; then
            continue
        fi
        pack_name="$(jq -r '.header.name // "?"' "$manifest_local" 2>/dev/null)"
        uuid="$(jq -r '.header.uuid // "?"' "$manifest_local" 2>/dev/null)"
        description="$(jq -r '.header.description // ""' "$manifest_local" 2>/dev/null)"
        marker="not Craftberry-generated — SKIPPED by clean"
        if [[ "$description" == "$CRAFTBERRY_MARKER" ]]; then
            marker="Craftberry-generated"
        fi
        active=""
        if [[ -n "$active_ids" ]] && grep -qx "$uuid" <<<"$active_ids"; then
            active=" [ACTIVE in $WORLD_NAME]"
        fi
        printf '  %-16s %-38s %-28s %s%s\n' "$name" "$uuid" "$marker" "$pack_name" "$active"
    done
}

cmd_status() {
    local world_name active_behavior="" active_resource=""
    if world_name="$(find_world_dir_name)"; then
        local world_dir="$AFC_BASE/minecraftWorlds/$world_name"
        echo "World: $WORLD_NAME"
        echo "  $world_dir"
        active_behavior="$(pack_ids_referenced_by_world "$world_dir" "world_behavior_packs.json")"
        active_resource="$(pack_ids_referenced_by_world "$world_dir" "world_resource_packs.json")"
    else
        echo "World: $WORLD_NAME not found (nothing currently references installed packs)"
    fi
    echo ""

    echo "=== Installed behavior packs ==="
    report_packs "behavior" "$active_behavior"
    echo ""
    echo "=== Installed resource packs ==="
    report_packs "resource" "$active_resource"
}

cmd_clean() {
    local confirmed="$1"
    local world_name=""
    world_name="$(find_world_dir_name)" || true

    if [[ "$confirmed" != "yes" ]]; then
        echo "This would permanently delete every Craftberry-generated pack folder under:"
        echo "  $AFC_BASE/behavior_packs"
        echo "  $AFC_BASE/resource_packs"
        if [[ -n "$world_name" ]]; then
            echo "and reset $AFC_BASE/minecraftWorlds/$world_name's world_behavior_packs.json / world_resource_packs.json to []."
        else
            echo "($WORLD_NAME does not currently exist, so there is no world JSON to reset.)"
        fi
        echo ""
        echo "Run 'status' first to review, then re-run with --yes to actually do this."
        exit 1
    fi

    if [[ -n "$world_name" ]]; then
        local world_dir="$AFC_BASE/minecraftWorlds/$world_name"
        echo "Resetting $WORLD_NAME's pack reference lists..."
        printf '[]' > "$OUTPUT_DIR/tmp/empty.json"
        afc put "$OUTPUT_DIR/tmp/empty.json" "$world_dir/world_behavior_packs.json" >/dev/null
        afc put "$OUTPUT_DIR/tmp/empty.json" "$world_dir/world_resource_packs.json" >/dev/null
    fi

    local removed=0 kept=0
    local kind name manifest_local description
    for kind in behavior resource; do
        for name in $(afc_ls "$AFC_BASE/${kind}_packs"); do
            if ! manifest_local="$(afc_get_to_temp "$AFC_BASE/${kind}_packs/$name/manifest.json" "${kind}-$name-manifest.json")"; then
                continue
            fi
            description="$(jq -r '.header.description // ""' "$manifest_local" 2>/dev/null)"
            if [[ "$description" == "$CRAFTBERRY_MARKER" ]]; then
                echo "Removing $kind pack: $name"
                afc rm -rf "$AFC_BASE/${kind}_packs/$name"
                removed=$((removed + 1))
            else
                kept=$((kept + 1))
            fi
        done
    done

    echo ""
    echo "Removed $removed Craftberry-generated pack folder(s); left $kept non-Craftberry folder(s) untouched."
}

main() {
    local mode="${1:-}"
    shift || true

    case "$mode" in
        -h|--help|help|"")
            usage
            exit 0
            ;;
    esac

    local confirmed="no"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yes)
                confirmed="yes"
                shift
                ;;
            *)
                echo "error: unknown argument '$1'" >&2
                usage
                exit 1
                ;;
        esac
    done

    case "$mode" in
        status|clean) ;;
        *)
            echo "error: unknown mode '$mode'" >&2
            usage
            exit 1
            ;;
    esac

    require_tool jq
    require_tool afcclient
    mkdir -p "$OUTPUT_DIR/tmp"

    case "$mode" in
        status)
            cmd_status
            ;;
        clean)
            cmd_clean "$confirmed"
            ;;
    esac
}

main "$@"
