#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_PATH="$ROOT_DIR/Craftberry.xcodeproj"
SCHEME="Craftberry"
OUTPUT_DIR="$ROOT_DIR/.build/minecraft-calibration"
SESSION_FILE="$OUTPUT_DIR/session.json"
XCODEBUILD_LOG="$OUTPUT_DIR/xcodebuild.log"
IPROXY_LOG="$OUTPUT_DIR/iproxy.log"
TRANSCRIPT="$OUTPUT_DIR/transcript.log"
RESULT_BUNDLE_DIR="$OUTPUT_DIR/result-bundles"
SCREENSHOT_DIR="$OUTPUT_DIR/screenshots"
XCODEBUILD_PID_FILE="$OUTPUT_DIR/xcodebuild.pid"
IPROXY_PID_FILE="$OUTPUT_DIR/iproxy.pid"
DERIVED_DATA="$OUTPUT_DIR/DerivedData"
MINECRAFT_BUNDLE_ID="com.mojang.minecraftpe"
DEVICE_PORT=8765
HOST_PORT=8765
CLEANUP_SCRIPT="$ROOT_DIR/scripts/minecraft-cleanup.sh"

physical_iphone_filter='[.result.devices[]? | select(.hardwareProperties.platform == "iOS" and .hardwareProperties.deviceType == "iPhone" and .hardwareProperties.reality == "physical" and .connectionProperties.tunnelState == "connected")]'

usage() {
    cat <<USAGE
Usage: scripts/minecraft-calibrate.sh <command> [args]

Interactive Minecraft calibration controller. Performs automatic Craftberry
export/import and cold-launch, then exposes a JSON controller on
127.0.0.1:${HOST_PORT} via iproxy for turn-by-turn driving.

Commands:
  start <scenario> [--break-at <id-or-name>]
        Start a calibration session for one scenario. Scenario is one of:
          emerald | redstone | weapon | armor
        (aliases: emerald, emeraldSword, redstone, redstoneToolSet,
         weapon, redstoneWeaponSet, armor, redstoneArmorSet)
        --break-at stops before the named step (id like config:12 or name).

  status
        Show the current cursor and last result via the device controller.

  list-steps
        List all phased steps (config + crafting) with stable ids.

  observe [--ocr]
        Capture a screenshot (and, with --ocr, Vision OCR text).

  step
        Execute the current step. Advances cursor on success, retains on failure.

  run-until <id-or-name>
        Run steps until just before the target. Stops immediately on failure.

  mark-complete
        Mark the current step complete without executing it (skip).

  select-step <id-or-name>
        Move the cursor to the target step. Does not restore Minecraft UI state.

  tap <x> <y>
  drag <x> <y> <endX> <endY>
  swipe-up
  keyboard-text <text>
  numeric-keyboard-text <text>
  chat-command <text>
  wait <seconds>
        Ad hoc actions. Never advance the cursor, even on success.

  stop [--keep-state]
        Terminate the calibration session. By default also terminates Minecraft
        and runs AFC cleanup (deletes Generated by Craftberry packs and the
        craftberry test world). --keep-state leaves Minecraft, packs, and world
        untouched for manual inspection.

Session state, logs, transcripts, result bundles, and decoded screenshots are
kept under .build/minecraft-calibration/. One session at a time is supported;
concurrent start attempts are refused. Host port ${HOST_PORT} is bound only to
127.0.0.1 via iproxy and the listener exists only during the calibration UI test.

Prerequisites: unlocked physical iPhone over USB, Developer Mode, Minecraft
installed, afcclient + jq + python3 + iproxy on PATH, valid signing.

USAGE
}

require_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: required tool '$1' was not found on PATH" >&2
        exit 1
    fi
}

discover_devices() {
    mkdir -p "$OUTPUT_DIR"
    local json_path="$OUTPUT_DIR/devices.json"
    xcrun devicectl list devices \
        --timeout 10 \
        --json-output "$json_path" \
        > "$OUTPUT_DIR/devices.txt"
    printf '%s\n' "$json_path"
}

select_device() {
    local json_path
    json_path="$(discover_devices)"

    if [[ -n "${DEVICE_ID:-}" ]]; then
        local matches
        matches="$(jq -r --arg id "$DEVICE_ID" "$physical_iphone_filter | map(select(.identifier == \$id)) | length" "$json_path")"
        if [[ "$matches" == "1" ]]; then
            printf '%s\n' "$DEVICE_ID"
            return
        fi
        echo "error: DEVICE_ID '$DEVICE_ID' is not a connected physical iPhone." >&2
        jq -r "$physical_iphone_filter | .[] | [.identifier, .deviceProperties.name] | @tsv" "$json_path" >&2
        exit 1
    fi

    local count
    count="$(jq -r "$physical_iphone_filter | length" "$json_path")"
    case "$count" in
        0)
            echo "error: no connected physical iPhones found." >&2
            jq -r "$physical_iphone_filter | if length==0 then \"no devices\" else .[] | [.identifier, .deviceProperties.name] | @tsv end" "$json_path" >&2
            exit 1
            ;;
        1)
            jq -r "$physical_iphone_filter | .[0].identifier" "$json_path"
            ;;
        *)
            echo "error: multiple connected physical iPhones found; set DEVICE_ID." >&2
            jq -r "$physical_iphone_filter | .[] | [.identifier, .deviceProperties.name] | @tsv" "$json_path" >&2
            exit 1
            ;;
    esac
}

is_session_active() {
    if [[ ! -f "$SESSION_FILE" ]]; then
        return 1
    fi
    local xcodebuild_pid iproxy_pid
    xcodebuild_pid="$(jq -r '.xcodebuild_pid // empty' "$SESSION_FILE" 2>/dev/null || true)"
    iproxy_pid="$(jq -r '.iproxy_pid // empty' "$SESSION_FILE" 2>/dev/null || true)"
    local alive=0
    if [[ -n "$xcodebuild_pid" ]] && kill -0 "$xcodebuild_pid" 2>/dev/null; then
        alive=1
    fi
    if [[ -n "$iproxy_pid" ]] && kill -0 "$iproxy_pid" 2>/dev/null; then
        alive=1
    fi
    # Also consider iproxy port conflict: if something is already listening on HOST_PORT
    if [[ "$alive" -eq 1 ]]; then
        return 0
    fi
    # Stale session file: pid gone but file remains — treat as stale.
    return 1
}

scenario_to_test_selector() {
    local scenario="$1"
    case "$scenario" in
        emerald|emeraldSword|emerald_sword)
            printf 'CraftberryUITests/MinecraftCalibrationUITests/testCalibrationEmeraldSword'
            ;;
        redstone|redstoneToolSet|redstone_tool_set|redstone-tool-set)
            printf 'CraftberryUITests/MinecraftCalibrationUITests/testCalibrationRedstoneToolSet'
            ;;
        weapon|redstoneWeaponSet|redstone_weapon_set|redstone-weapon-set|redstoneWeapon)
            printf 'CraftberryUITests/MinecraftCalibrationUITests/testCalibrationRedstoneWeaponSet'
            ;;
        armor|redstoneArmorSet|redstone_armor_set|redstone-armor-set|redstoneArmor)
            printf 'CraftberryUITests/MinecraftCalibrationUITests/testCalibrationRedstoneArmorSet'
            ;;
        *)
            echo "error: unknown scenario '$scenario' (expected emerald, redstone, weapon, or armor)." >&2
            exit 1
            ;;
    esac
}

# Send one JSON request (newline-delimited) to 127.0.0.1:HOST_PORT and print response.
send_request() {
    local json="$1"
    local response
    # Use python3 for reliable TCP with timeout; nc varies by platform.
    response="$(python3 -c "
import socket, sys, json
host='127.0.0.1'
port=${HOST_PORT}
payload=sys.argv[1] + '\n'
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(15)
try:
    s.connect((host, port))
    s.sendall(payload.encode('utf-8'))
    # Read until newline or EOF.
    data=b''
    s.settimeout(30)
    while True:
        chunk=s.recv(65536)
        if not chunk:
            break
        data+=chunk
        if b'\n' in data:
            break
    sys.stdout.write(data.decode('utf-8', errors='replace'))
except Exception as e:
    sys.stderr.write(f\"error: could not reach calibration controller on 127.0.0.1:${HOST_PORT}: {e}\n\")
    sys.exit(1)
finally:
    try:
        s.close()
    except:
        pass
" "$json" 2>&1)" || {
        echo "$response" >&2
        echo '{"success":false,"error":"could not reach calibration controller — is the session running? Check .build/minecraft-calibration/xcodebuild.log and iproxy.log"}' | python3 -m json.tool 2>/dev/null || echo "$response"
        return 1
    }
    echo "$response"
}

pretty_and_save() {
    local json_line="$1"
    local label="$2"
    local timestamp
    timestamp="$(date +%Y%m%d-%H%M%S)"
    echo "$json_line" | python3 -m json.tool 2>/dev/null || echo "$json_line"
    # Append to transcript
    {
        echo "[$timestamp] $label"
        echo "$json_line" | python3 -m json.tool 2>/dev/null || echo "$json_line"
        echo "---"
    } >> "$TRANSCRIPT"
    # Also save raw result bundle
    mkdir -p "$OUTPUT_DIR/result-bundles"
    echo "$json_line" > "$OUTPUT_DIR/result-bundles/${timestamp}-${label}.json"
    # Decode screenshot if present
    local b64
    b64="$(echo "$json_line" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('screenshotBase64',''))" 2>/dev/null || true)"
    if [[ -n "$b64" && "$b64" != "" ]]; then
        mkdir -p "$SCREENSHOT_DIR"
        local png_path="$SCREENSHOT_DIR/${timestamp}-${label}.png"
        echo "$b64" | python3 -c "import sys, base64; data=base64.b64decode(sys.stdin.read().strip()); open(sys.argv[1],'wb').write(data)" "$png_path" 2>/dev/null && echo "Screenshot saved: $png_path" >&2 || true
    fi
}

cmd_start() {
    local scenario="${1:-}"
    shift || true
    local break_at=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --break-at)
                break_at="${2:-}"
                if [[ -z "$break_at" ]]; then
                    echo "error: --break-at requires a value" >&2
                    exit 1
                fi
                shift 2
                ;;
            *)
                echo "error: unknown argument '$1' for start" >&2
                usage >&2
                exit 1
                ;;
        esac
    done
    if [[ -z "$scenario" ]]; then
        echo "error: start requires a scenario (emerald, redstone, weapon, armor)" >&2
        usage >&2
        exit 1
    fi

    if is_session_active; then
        echo "error: a calibration session is already active." >&2
        echo "Run 'scripts/minecraft-calibrate.sh status' to inspect it, or 'scripts/minecraft-calibrate.sh stop' to end it before starting another." >&2
        echo "Session file: $SESSION_FILE" >&2
        cat "$SESSION_FILE" 2>/dev/null | python3 -m json.tool 2>/dev/null || cat "$SESSION_FILE" 2>/dev/null || true
        exit 1
    fi
    # Check port availability
    if python3 -c "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1', ${HOST_PORT})); s.close()" 2>/dev/null; then
        echo "error: 127.0.0.1:${HOST_PORT} is already in use. Another process may be bound to the calibration port." >&2
        echo "Stop the existing session or free the port before starting." >&2
        exit 1
    fi

    require_tool jq
    require_tool xcrun
    require_tool python3
    require_tool iproxy

    local device_id
    device_id="$(select_device)"
    local test_selector
    test_selector="$(scenario_to_test_selector "$scenario")"

    mkdir -p "$OUTPUT_DIR" "$RESULT_BUNDLE_DIR" "$SCREENSHOT_DIR"
    : > "$TRANSCRIPT"
    : > "$XCODEBUILD_LOG"
    : > "$IPROXY_LOG"

    local timestamp result_path
    timestamp="$(date +%Y%m%d-%H%M%S)"
    result_path="$OUTPUT_DIR/${scenario}-${timestamp}.xcresult"

    echo "Starting calibration session: scenario=$scenario selector=$test_selector device=$device_id" | tee -a "$TRANSCRIPT"
    if [[ -n "$break_at" ]]; then
        echo "Break-at: $break_at" | tee -a "$TRANSCRIPT"
    fi

    # Start iproxy in background
    echo "Starting iproxy ${HOST_PORT}:${DEVICE_PORT} (device $device_id)..." | tee -a "$TRANSCRIPT"
    # iproxy (libimobiledevice) expects the USB UDID (idevice_id), not the CoreDevice identifier.
    local usb_udid
    usb_udid="$(idevice_id -l 2>/dev/null | head -n1 || true)"
    set +e
    if [[ -n "$usb_udid" ]]; then
        iproxy -u "$usb_udid" "${HOST_PORT}:${DEVICE_PORT}" > "$IPROXY_LOG" 2>&1 &
    else
        iproxy "${HOST_PORT}:${DEVICE_PORT}" > "$IPROXY_LOG" 2>&1 &
    fi
    local iproxy_pid=$!
    set -e
    echo "$iproxy_pid" > "$IPROXY_PID_FILE"
    sleep 1
    if ! kill -0 "$iproxy_pid" 2>/dev/null; then
        echo "error: iproxy failed to start. Check $IPROXY_LOG" >&2
        cat "$IPROXY_LOG" >&2 || true
        exit 1
    fi

    # Determine whether the craftberry test world already exists (AFC probe,
    # while Minecraft is still not running cleanly? We terminate concept not
    # needed before calibration start; probe fails open to creation.
    local reuse_world="0"
    if [[ -f "$ROOT_DIR/scripts/minecraft-cleanup.sh" ]] && command -v afcclient >/dev/null 2>&1; then
        local tmp_probe
        tmp_probe="$(mktemp)"
        if "$CLEANUP_SCRIPT" status >"$tmp_probe" 2>&1 && ! grep -q "not found" "$tmp_probe" && grep -q "minecraftWorlds/" "$tmp_probe"; then
            reuse_world="1"
            echo "Existing craftberry test world found via AFC — calibration will reuse it." | tee -a "$TRANSCRIPT"
        else
            echo "No existing craftberry test world via AFC — calibration will create one." | tee -a "$TRANSCRIPT"
        fi
        rm -f "$tmp_probe"
    else
        echo "AFC probe unavailable — calibration will attempt world creation." | tee -a "$TRANSCRIPT"
    fi

    # Start xcodebuild in background
    echo "Running xcodebuild test $test_selector ..." | tee -a "$TRANSCRIPT"
    local derived_arg=(-derivedDataPath "$DERIVED_DATA" -resultBundlePath "$result_path")
    local env_args=(MINECRAFT_CALIBRATION_REUSE_WORLD="$reuse_world")
    if [[ -n "$break_at" ]]; then
        env_args+=(MINECRAFT_CALIBRATION_BREAK_AT="$break_at")
    fi

    set +e
    # shellcheck disable=SC2086
    env "${env_args[@]}" xcodebuild \
        -project "$PROJECT_PATH" \
        -scheme "$SCHEME" \
        -configuration Debug \
        -destination "platform=iOS,id=$device_id" \
        "${derived_arg[@]}" \
        -allowProvisioningUpdates \
        -only-testing:"$test_selector" \
        test > "$XCODEBUILD_LOG" 2>&1 &
    local xcodebuild_pid=$!
    set -e
    echo "$xcodebuild_pid" > "$XCODEBUILD_PID_FILE"

    # Write session file
    cat > "$SESSION_FILE" <<SESSION
{
  "scenario": "$scenario",
  "test_selector": "$test_selector",
  "device_id": "$device_id",
  "break_at": "$break_at",
  "xcodebuild_pid": $xcodebuild_pid,
  "iproxy_pid": $iproxy_pid,
  "result_path": "$result_path",
  "started_at": "$timestamp",
  "host_port": $HOST_PORT,
  "device_port": $DEVICE_PORT
}
SESSION

    echo "Session started. Waiting for calibration controller on 127.0.0.1:${HOST_PORT}..." | tee -a "$TRANSCRIPT"
    echo "Logs: $XCODEBUILD_LOG , $IPROXY_LOG" | tee -a "$TRANSCRIPT"
    echo "Result bundle: $result_path" | tee -a "$TRANSCRIPT"

    # Poll for readiness: try status until it responds or xcodebuild exits.
    local attempts=0
    local max_attempts=60
    while [[ $attempts -lt $max_attempts ]]; do
        if ! kill -0 "$xcodebuild_pid" 2>/dev/null; then
            # xcodebuild exited early — check if it succeeded or failed
            echo "error: xcodebuild exited before the calibration controller became ready." >&2
            echo "Check $XCODEBUILD_LOG for details. Preserving session file for inspection." >&2
            tail -n 80 "$XCODEBUILD_LOG" >&2 || true
            echo '{"success":false,"error":"xcodebuild exited before controller ready — check xcodebuild.log"}' | python3 -m json.tool 2>/dev/null || true
            exit 1
        fi
        if python3 -c "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1', ${HOST_PORT})); s.sendall(b'{\"command\":\"status\"}\n'); s.settimeout(2); d=s.recv(65536); s.close(); exit(0 if d else 1)" 2>/dev/null; then
            break
        fi
        sleep 2
        attempts=$((attempts+1))
        printf '.' >&2
    done
    echo "" >&2

    if [[ $attempts -ge $max_attempts ]]; then
        echo "error: calibration controller did not become ready within $((max_attempts*2))s." >&2
        echo "The test may still be in Craftberry export/import. Check $XCODEBUILD_LOG" >&2
        echo "Session remains active — use 'scripts/minecraft-calibrate.sh status' to poll again or 'stop' to terminate." >&2
        exit 1
    fi

    echo "Calibration controller ready on 127.0.0.1:${HOST_PORT}" | tee -a "$TRANSCRIPT"
    # Print initial status
    local status_json
    status_json="$(python3 -c "
import socket, sys
s=socket.socket()
s.settimeout(5)
s.connect(('127.0.0.1', ${HOST_PORT}))
s.sendall(b'{\"command\":\"status\"}\n')
data=b''
s.settimeout(5)
while True:
    c=s.recv(65536)
    if not c: break
    data+=c
    if b'\n' in data: break
sys.stdout.write(data.decode())
")"
    pretty_and_save "$status_json" "start-status"

    echo "Session started successfully. Use 'scripts/minecraft-calibrate.sh status' to inspect, 'step' / 'run-until' to drive, and 'stop' to end." | tee -a "$TRANSCRIPT"
}

cmd_status() {
    require_tool python3
    if [[ ! -f "$SESSION_FILE" ]]; then
        echo '{"success":false,"error":"no active calibration session — run start first"}' | python3 -m json.tool
        exit 1
    fi
    local req='{"command":"status"}'
    local resp
    if ! resp="$(send_request "$req")"; then
        echo "error: session file exists but controller is unreachable. Process may have exited." >&2
        echo "Check $XCODEBUILD_LOG and $IPROXY_LOG" >&2
        if ! kill -0 "$(jq -r '.xcodebuild_pid // empty' "$SESSION_FILE" 2>/dev/null)" 2>/dev/null; then
            echo "xcodebuild process is not running (stale session)." >&2
        fi
        exit 1
    fi
    pretty_and_save "$resp" "status"
}

cmd_list_steps() {
    local req='{"command":"list_steps"}'
    local resp
    resp="$(send_request "$req")" || exit 1
    pretty_and_save "$resp" "list-steps"
}

cmd_observe() {
    local ocr="false"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --ocr) ocr="true"; shift ;;
            *) echo "error: unknown argument '$1' for observe" >&2; exit 1 ;;
        esac
    done
    local req
    if [[ "$ocr" == "true" ]]; then
        req='{"command":"observe","ocr":true}'
    else
        req='{"command":"observe","ocr":false}'
    fi
    # Observe also requests screenshot (controller always includes it for observe)
    # Our controller's observe includes screenshot; we request it explicitly.
    # Modify controller to include screenshotBase64 for observe — done.
    # Send and handle.
    local resp
    # We need to ensure observe returns screenshot. Our controller's observe already does.
    # But we need to map to includeScreenshot. Implement as separate via python.
    # Actually send observe command; controller will return screenshotBase64.
    resp="$(send_request "$req")" || exit 1
    # For observe we want screenshot always, so re-send with includeScreenshot hint if controller didn't include it.
    # Our controller's observe path sets includeScreenshot true, so it's fine.
    pretty_and_save "$resp" "observe"
}

# Generic helper for single-command requests
cmd_simple() {
    local req="$1"
    local label="$2"
    local resp
    resp="$(send_request "$req")" || exit 1
    pretty_and_save "$resp" "$label"
}

cmd_tap() {
    if [[ $# -ne 2 ]]; then echo "error: tap requires <x> <y>" >&2; exit 1; fi
    local x="$1" y="$2"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'tap','x':float(sys.argv[1]),'y':float(sys.argv[2])}))" "$x" "$y")"
    cmd_simple "$req" "tap"
}

cmd_drag() {
    if [[ $# -ne 4 ]]; then echo "error: drag requires <x> <y> <endX> <endY>" >&2; exit 1; fi
    local x="$1" y="$2" endX="$3" endY="$4"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'drag','x':float(sys.argv[1]),'y':float(sys.argv[2]),'endX':float(sys.argv[3]),'endY':float(sys.argv[4])}))" "$x" "$y" "$endX" "$endY")"
    cmd_simple "$req" "drag"
}

cmd_swipe_up() {
    cmd_simple '{"command":"swipe_up"}' "swipe-up"
}

cmd_keyboard_text() {
    if [[ $# -lt 1 ]]; then echo "error: keyboard-text requires <text>" >&2; exit 1; fi
    local text="$*"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'keyboard_text','text':sys.argv[1]}))" "$text")"
    cmd_simple "$req" "keyboard-text"
}

cmd_numeric_keyboard_text() {
    if [[ $# -lt 1 ]]; then echo "error: numeric-keyboard-text requires <text>" >&2; exit 1; fi
    local text="$*"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'numeric_keyboard_text','text':sys.argv[1]}))" "$text")"
    cmd_simple "$req" "numeric-keyboard-text"
}

cmd_chat_command() {
    if [[ $# -lt 1 ]]; then echo "error: chat-command requires <text>" >&2; exit 1; fi
    local text="$*"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'chat_command','text':sys.argv[1]}))" "$text")"
    cmd_simple "$req" "chat-command"
}

cmd_wait() {
    if [[ $# -ne 1 ]]; then echo "error: wait requires <seconds>" >&2; exit 1; fi
    local seconds="$1"
    local req
    req="$(python3 -c "import json, sys; print(json.dumps({'command':'wait','seconds':float(sys.argv[1])}))" "$seconds")"
    cmd_simple "$req" "wait"
}

terminate_minecraft_on_device() {
    local device_id="$1"
    local processes_json="$OUTPUT_DIR/minecraft-processes.json"
    local processes_log="$OUTPUT_DIR/minecraft-processes.log"
    if ! xcrun devicectl device info processes \
        --device "$device_id" \
        --timeout 15 \
        --json-output "$processes_json" \
        --log-output "$processes_log" \
        >/dev/null 2>&1; then
        echo "warning: could not list device processes; skipping Minecraft termination" >&2
        return 0
    fi
    local pids
    pids="$(jq -r --arg bundle "$MINECRAFT_BUNDLE_ID" '
        .. | objects
        | select(
            ((.bundleIdentifier? // .bundleID? // .applicationIdentifier? // "") == $bundle)
            or ((.executable? // "") | test("/Minecraft[.]app/Minecraft$|minecraftpe"; "i"))
        )
        | (.pid? // .processIdentifier? // empty)
    ' "$processes_json" | sort -u)"
    if [[ -z "$pids" ]]; then
        echo "Minecraft is not running." | tee -a "$TRANSCRIPT"
        return 0
    fi
    local pid
    for pid in $pids; do
        echo "Terminating Minecraft process $pid..." | tee -a "$TRANSCRIPT"
        xcrun devicectl device process terminate \
            --device "$device_id" \
            --pid "$pid" \
            --kill \
            --timeout 15 \
            >/dev/null || true
    done
}

cmd_stop() {
    local keep_state="no" delete_world="no"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --keep-state) keep_state="yes"; shift ;;
            --delete-world|--fresh-world) delete_world="yes"; shift ;;
            --keep-world) delete_world="no"; shift ;;
            *) echo "error: unknown argument '$1' for stop" >&2; exit 1 ;;
        esac
    done
    if [[ "$keep_state" == "yes" && "$delete_world" == "yes" ]]; then
        echo "error: --keep-state and --delete-world are mutually exclusive" >&2
        exit 1
    fi

    if [[ ! -f "$SESSION_FILE" ]]; then
        echo "error: no active calibration session to stop." >&2
        exit 1
    fi

    local device_id xcodebuild_pid iproxy_pid
    device_id="$(jq -r '.device_id // empty' "$SESSION_FILE" 2>/dev/null || true)"
    xcodebuild_pid="$(jq -r '.xcodebuild_pid // empty' "$SESSION_FILE" 2>/dev/null || true)"
    iproxy_pid="$(jq -r '.iproxy_pid // empty' "$SESSION_FILE" 2>/dev/null || true)"

    echo "Stopping calibration session..." | tee -a "$TRANSCRIPT"

    # Kill iproxy
    if [[ -n "$iproxy_pid" ]] && kill -0 "$iproxy_pid" 2>/dev/null; then
        echo "Terminating iproxy ($iproxy_pid)..." | tee -a "$TRANSCRIPT"
        kill "$iproxy_pid" 2>/dev/null || true
        sleep 1
        kill -9 "$iproxy_pid" 2>/dev/null || true
    fi
    rm -f "$IPROXY_PID_FILE"

    # Kill xcodebuild
    if [[ -n "$xcodebuild_pid" ]] && kill -0 "$xcodebuild_pid" 2>/dev/null; then
        echo "Terminating xcodebuild ($xcodebuild_pid)..." | tee -a "$TRANSCRIPT"
        kill "$xcodebuild_pid" 2>/dev/null || true
        sleep 2
        kill -9 "$xcodebuild_pid" 2>/dev/null || true
        # Also kill any child test runner processes
        pkill -P "$xcodebuild_pid" 2>/dev/null || true
    fi
    rm -f "$XCODEBUILD_PID_FILE"

    # Give device time to settle
    sleep 2

    if [[ "$keep_state" == "yes" ]]; then
        echo "Keeping Minecraft, packs, and world untouched (--keep-state)." | tee -a "$TRANSCRIPT"
    else
        if [[ -n "$device_id" ]]; then
            terminate_minecraft_on_device "$device_id"
            if [[ "$delete_world" == "yes" ]]; then
                echo "Running AFC cleanup (Generated by Craftberry packs + craftberry test world, INCLUDING world deletion)..." | tee -a "$TRANSCRIPT"
                set +e
                "$CLEANUP_SCRIPT" clean --delete-world --yes >> "$TRANSCRIPT" 2>&1
                local cleanup_status=$?
                set -e
            else
                echo "Running AFC cleanup (Generated by Craftberry packs only, world preserved)..." | tee -a "$TRANSCRIPT"
                set +e
                "$CLEANUP_SCRIPT" clean --yes >> "$TRANSCRIPT" 2>&1
                local cleanup_status=$?
                set -e
            fi
            if [[ $cleanup_status -ne 0 ]]; then
                echo "warning: AFC cleanup failed with status $cleanup_status — check $TRANSCRIPT" >&2
            else
                echo "AFC cleanup complete." | tee -a "$TRANSCRIPT"
            fi
        else
            echo "warning: device_id unknown, skipping Minecraft termination and AFC cleanup" >&2
        fi
    fi

    # Preserve logs, remove session file
    echo "Session stopped. Logs kept under $OUTPUT_DIR" | tee -a "$TRANSCRIPT"
    rm -f "$SESSION_FILE"
}

main() {
    mkdir -p "$OUTPUT_DIR" "$RESULT_BUNDLE_DIR" "$SCREENSHOT_DIR"
    case "${1:-}" in
        start)
            shift
            cmd_start "$@"
            ;;
        status)
            cmd_status
            ;;
        list-steps|list_steps)
            cmd_list_steps
            ;;
        observe)
            shift
            cmd_observe "$@"
            ;;
        step)
            cmd_simple '{"command":"step"}' "step"
            ;;
        run-until|run_until)
            if [[ $# -lt 2 ]]; then echo "error: run-until requires <id-or-name>" >&2; exit 1; fi
            local target="${2:-}"
            if [[ -z "$target" ]]; then echo "error: run-until requires <id-or-name>" >&2; exit 1; fi
            local req
            req="$(python3 -c "import json, sys; print(json.dumps({'command':'run_until','target':sys.argv[1]}))" "$target")"
            cmd_simple "$req" "run-until"
            ;;
        mark-complete|mark_complete)
            cmd_simple '{"command":"mark_complete"}' "mark-complete"
            ;;
        select-step|select_step)
            if [[ $# -lt 2 ]]; then echo "error: select-step requires <id-or-name>" >&2; exit 1; fi
            local target="${2:-}"
            local req2
            req2="$(python3 -c "import json, sys; print(json.dumps({'command':'select_step','target':sys.argv[1]}))" "$target")"
            cmd_simple "$req2" "select-step"
            ;;
        tap)
            shift
            cmd_tap "$@"
            ;;
        drag)
            shift
            cmd_drag "$@"
            ;;
        swipe-up|swipe_up)
            cmd_swipe_up
            ;;
        keyboard-text|keyboard_text)
            shift
            cmd_keyboard_text "$@"
            ;;
        numeric-keyboard-text|numeric_keyboard_text)
            shift
            cmd_numeric_keyboard_text "$@"
            ;;
        chat-command|chat_command)
            shift
            cmd_chat_command "$@"
            ;;
        wait)
            shift
            cmd_wait "$@"
            ;;
        stop)
            shift
            cmd_stop "$@"
            ;;
        -h|--help|help|"")
            usage
            ;;
        *)
            echo "error: unknown command '$1'" >&2
            usage >&2
            exit 1
            ;;
    esac
}

main "$@"
